export {default as Login} from './Login'
export {default as Logout} from './Signup'
export {default as ForgotPassword} from './ForgotPassword'
export {default as UpdateProfile} from './UpdateProfile'
export {default as Signup} from './Signup'