export const authConstant = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT'
}

export const userConstants ={
  GET_REALTIME_USERS: 'GET_REALTIME_USERS',
  GET_REALTIME_MESSAGES: 'GET_REALTIME_MESSAGES',
  GET_STATUS_CURRENT_USER: 'GET_STATUS_CURRENT_USER',
  SET_DATA_CURRENT_USER: 'SET_DATA_CURRENT_USER',
  GET_REALTIME_MESSAGES_REQUEST: 'GET_REALTIME_MESSAGES_REQUEST'
}

export const GET_CONVERSATIONS = 'GET_CONVERSATIONS'
export const SET_REAL_USERS = 'SET_REAL_USERS'
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'
export const IS_LOADED = 'IS_LOADED'
export const GET_WROTE_USERS_IDS = 'GET_WROTE_USERS_IDS'
export const SET_SELECTED_USER = 'SET_SELECTED_USER'
export const SET_SELECTED_USER_NULL = 'SET_SELECTED_USER_NULL'
export const GET_WROTE_USERS = 'GET_WROTE_USERS'
export const SET_DISTANCE_TO_TARGET = 'SET_DISTANCE_TO_TARGET'
export const GET_WROTE_USERS_AND_READ = 'GET_WROTE_USERS_AND_READ'
export const GET_ACTIVE_CHAT_WITH_USERS = 'GET_ACTIVE_CHAT_WITH_USERS'