export const authConstant = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT'
}

export const userConstants ={
  GET_REALTIME_USERS: 'GET_REALTIME_USERS',
  GET_REALTIME_MESSAGES: 'GET_REALTIME_MESSAGES',
  GET_STATUS_CURRENT_USER: 'GET_STATUS_CURRENT_USER',
  SET_DATA_CURRENT_USER: 'SET_DATA_CURRENT_USER'
}