export const authConstant = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT'
}

export const userConstants ={
  GET_REALTIME_USERS: 'GET_REALTIME_USERS',
  GET_REALTIME_MESSAGES: 'GET_REALTIME_MESSAGES',
  GET_STATUS_CURRENT_USER: 'GET_STATUS_CURRENT_USER',
  SET_DATA_CURRENT_USER: 'SET_DATA_CURRENT_USER',
  GET_REALTIME_MESSAGES_REQUEST: 'GET_REALTIME_MESSAGES_REQUEST'
}

export const GET_CONVERSATIONS = 'GET_CONVERSATIONS'
export const SET_REAL_USERS = 'SET_REAL_USERS'
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'